steps:
  - id: Build
    name: 'gcr.io/cloud-builders/gradle'
    entrypoint: gradle
    args: ['jib']
  - id: Deploy to GKE
    name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - run
      - --filename=./kubernetes.yaml
      - --cluster=cluster-1
      - --location=us-west1-c # region or zone
