spring:
  application:
    name: text-to-speech-service
  codec:
    max-in-memory-size: 10MB

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

