jumoresques:
  refresh:
    rate: 3600000 #one hour in ms
spring:
  application:
    name: jumoresques-refresher-service
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

gcp:
  project-id: alexa-jumoresques
  bucket-name: audio-jumoresques
  object-name: jumoresques
